### ISSUE TITLE
Bench editing broken

### ISSUE THREAD

**Issue by arizonagroovejet** [openbenches/openbenches.org#343]
Steps to recreate:

Go to https://openbenches.org/admin/no-mediatypes click any of the links to benches.

Result:

```
An Error Occurred

"500 - Internal Server Error"

Something is broken. Please [let us know what you were doing when this error occurred](https://github.com/openbenches/openbenches.org/issues/new).

I will fix it as soon as possible. Sorry for any inconvenience caused.
Details
#0 /home/openbenc/public_html/vendor/symfony/dependency-injection/Container.php(361): Symfony\Component\DependencyInjection\EnvVarProcessor->getEnv()
#1 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/getAuth0Service.php(24): Symfony\Component\DependencyInjection\Container->getEnv()
#2 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/App_KernelProdContainer.php(110): Container7WJeMxr\getAuth0Service::do()
#3 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/getAuth0_AuthenticatorService.php(20): Container7WJeMxr\App_KernelProdContainer->load()
#4 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/App_KernelProdContainer.php(110): Container7WJeMxr\getAuth0_AuthenticatorService::do()
#5 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/getSecurity_Authenticator_Manager_EditService.php(20): Container7WJeMxr\App_KernelProdContainer->load()
#6 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/App_KernelProdContainer.php(110): Container7WJeMxr\getSecurity_Authenticator_Manager_EditService::do()
#7 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/getSecurity_Firewall_Authenticator_EditService.php(20): Container7WJeMxr\App_KernelProdContainer->load()
#8 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/App_KernelProdContainer.php(110): Container7WJeMxr\getSecurity_Firewall_Authenticator_EditService::do()
#9 /home/openbenc/public_html/var/cache/prod/Container7WJeMxr/getSecurity_Firewall_Map_Context_EditService.php(23): Container7WJeMxr\App_KernelProdContainer->load()
#10 /home/openbenc/public_html/vendor/symfony/security-http/Firewall.php(74): Container7WJeMxr\getSecurity_Firewall_Map_Context_EditService::Container7WJeMxr\{closure}()
#11 /home/openbenc/public_html/vendor/symfony/security-http/Firewall.php(115): Symfony\Component\Security\Http\Firewall->Symfony\Component\Security\Http\{closure}()
#12 /home/openbenc/public_html/vendor/symfony/security-http/Firewall.php(92): Symfony\Component\Security\Http\Firewall->callListeners()
#13 /home/openbenc/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(246): Symfony\Component\Security\Http\Firewall->onKernelRequest()
#14 /home/openbenc/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()
#15 /home/openbenc/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#16 /home/openbenc/public_html/vendor/symfony/http-kernel/HttpKernel.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#17 /home/openbenc/public_html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#18 /home/openbenc/public_html/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle()
#19 /home/openbenc/public_html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#20 /home/openbenc/public_html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#21 /home/openbenc/public_html/public/index.php(5): require_once('/home/openbenc/...')
#22 {main}
```

**Comment by edent** [comment]
Thanks - I'd forgotten to regenerate a secret. Now fixed.
