### ISSUE TITLE
500 Error 

### ISSUE THREAD

**Issue by gam3** [openbenches/openbenches.org#370]
Getting the following error, as you likely already know.  Tried on Chrome and Firefox.
```
An Error Occurred
"500 - Internal Server Error"

Something is broken. Please [let us know what you were doing when this error occurred](https://github.com/openbenches/openbenches.org/issues/new).

I will fix it as soon as possible. Sorry for any inconvenience caused.

Details
#0 /home/openbenc/public_html/vendor/symfony/http-kernel/Controller/ControllerResolver.php(128): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->instantiateController()
#1 /home/openbenc/public_html/vendor/symfony/http-kernel/Controller/ControllerResolver.php(96): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController()
#2 /home/openbenc/public_html/vendor/symfony/http-kernel/HttpKernel.php(164): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController()
#3 /home/openbenc/public_html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#4 /home/openbenc/public_html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle()
#5 /home/openbenc/public_html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#6 /home/openbenc/public_html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#7 /home/openbenc/public_html/public/index.php(5): require_once('/home/openbenc/...')
#8 {main}
```
![screen-2024-07-02-18-05-17](https://github.com/openbenches/openbenches.org/assets/99491/d77b4759-9d39-4bb0-ad8b-0059a5438f70)

**Comment by edent** [comment]
Thanks - a botched upgrade was rolled back.
